### ISSUE TITLE
Expires param

### ISSUE THREAD

**Issue by volodchenkov** [celery/django-celery-beat#104] opened 2017-12-11 19:24 UTC
How can I pass expires param (in seconds) to PeriodicTask from django admin?

**Comment by DEKHTIARJonathan** [comment] 2018-03-13 09:47
I have the same issue.

**Comment by babu-upcomer** [comment] 2018-03-31 18:31
Expires as a datetime field in the CMS doesn't make any sense for a scheduled task. It should be an IntegerFiedl() with the seconds to expire.

**Comment by cank** [comment] 2018-09-21 15:41
I don't think it is properly supported.

https://github.com/celery/django-celery-beat/blob/master/django_celery_beat/schedulers.py#L152-L176

Looks like `expires` doesn't even make it into the list of `_unpack_options`.

**Comment by Skeen** [comment] 2018-12-04 08:31
+1, I expected the expires functionality to work like this, but was surprised to find that it's a datetime field.

**Comment by Skeen** [comment] 2018-12-04 08:38
Seems like a duplicate of #19

**Comment by auvipy** [comment] 2018-12-11 10:19
hopefully this was fixed in 1.4

**Closed by auvipy** 2018-12-11 10:19 UTC
