### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'is_due'

### ISSUE THREAD

**Issue by newerBkl** [celery/django-celery-beat#88] opened 2017-10-17 11:33 UTC
Hi, we're running Django==1.11.3 &celery==4.1.0 & django-celery-beat==1.0.1  on only one server.
we've being experiencing this error ：
`AttributeError: 'NoneType' object has no attribute 'is_due'`
The Traceback is:
```
2017-10-17 09:44:31,975: ERROR/Beat] Process Beat
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/billiard/process.py", line 327, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/site-packages/celery/beat.py", line 634, in run
    self.service.start(embedded_process=True)
  File "/usr/local/lib/python2.7/site-packages/celery/beat.py", line 558, in start
    interval = self.scheduler.tick()
  File "/usr/local/lib/python2.7/site-packages/celery/beat.py", line 265, in tick
    self.populate_heap()
  File "/usr/local/lib/python2.7/site-packages/celery/beat.py", line 246, in populate_heap
    for e in values(self.schedule)]
  File "/usr/local/lib/python2.7/site-packages/django_celery_beat/schedulers.py", line 99, in is_due
    return self.schedule.is_due(self.last_run_at)
AttributeError: 'NoneType' object has no attribute 'is_due'
[2017-10-17 09:44:32,006: WARNING/Beat] Process Beat:
[2017-10-17 09:44:32,007: WARNING/Beat] Traceback (most recent call last):
[2017-10-17 09:44:32,007: WARNING/Beat] File "/usr/local/lib/python2.7/site-packages/billiard/process.py", line 327, in _bootstrap
[2017-10-17 09:44:32,007: WARNING/Beat] self.run()
[2017-10-17 09:44:32,007: WARNING/Beat] File "/usr/local/lib/python2.7/site-packages/celery/beat.py", line 634, in run
[2017-10-17 09:44:32,007: WARNING/Beat] self.service.start(embedded_process=True)
[2017-10-17 09:44:32,007: WARNING/Beat] File "/usr/local/lib/python2.7/site-packages/celery/beat.py", line 558, in start
[2017-10-17 09:44:32,007: WARNING/Beat] interval = self.scheduler.tick()
[2017-10-17 09:44:32,008: WARNING/Beat] File "/usr/local/lib/python2.7/site-packages/celery/beat.py", line 265, in tick
[2017-10-17 09:44:32,008: WARNING/Beat] self.populate_heap()
[2017-10-17 09:44:32,008: WARNING/Beat] File "/usr/local/lib/python2.7/site-packages/celery/beat.py", line 246, in populate_heap
[2017-10-17 09:44:32,008: WARNING/Beat] for e in values(self.schedule)]
[2017-10-17 09:44:32,008: WARNING/Beat] File "/usr/local/lib/python2.7/site-packages/django_celery_beat/schedulers.py", line 99, in is_due
[2017-10-17 09:44:32,008: WARNING/Beat] return self.schedule.is_due(self.last_run_at)
[2017-10-17 09:44:32,008: WARNING/Beat] AttributeError: 'NoneType' object has no attribute 'is_due'
```

Could you please check out and tell us what could be causing this ?

**Comment by hartwork** [comment] 2019-04-16 21:50
This affects the latest release 1.4.0 as well. To reproduce the problem, add an instance of `PeriodicTask` with `crontab=None` to the database which is allowed by the model:
https://github.com/celery/django-celery-beat/blob/2acd6a225f5f4cd7667a4abb17651aadf985b1c0/django_celery_beat/models.py#L271
Maybe `null=True` can be dropped from the model for a fix?

Thanks!

**Comment by liquidpele** [comment] 2019-04-17 13:50
The help text on the field specifies that you should chose between the interval and crontab FK, so it has to remain nullable.  Can you provide the exact data you entered for the model?  Did you manually enter the data without doing validation (e.g. https://github.com/celery/django-celery-beat/blob/2acd6a225f5f4cd7667a4abb17651aadf985b1c0/django_celery_beat/models.py#L335)?

**Comment by hartwork** [comment] 2019-04-17 14:00
Hi!

The model was created from Python code passing `None` for all of them using django-celery-beat 1.1.1 I think (but would need to check again at work), where `.save` does not seem to prevent creation of an object like that. I guess `.validate_unique` was not called? Could it be that `.save` would need to call `.validate_unique` manually, to ensure consistent data for models created from code?

**Comment by liquidpele** [comment] 2019-04-17 15:16
Yea, so that's an invalid model then.  I'll close the issue and if you want to send us a PR to make this a little less hard to run into we'd appreciate it!

**Comment by hartwork** [comment] 2019-04-17 16:08
This issue caused a big problem to me in production yesterday — even with upgrading to the latest version — so I was really hoping for a more co-operative answer than "patches welcome".

> Yea, so that's an invalid model then.

If it passed `.save` it's not an invalid model.

> Could it be that .save would need to call .validate_unique, to ensure consistent data for models created from code?

@liquidpele that^^ question remains unanswered

**Comment by liquidpele** [comment] 2019-04-17 16:37
Apologies, didn't mean to sound like I was blowing you off.  

It looks like validate_unique is only called by the Form used by the admin.py siteadmin page.   I just joined the project and so I'm not super familiar with how others use celery, but I'd recommend using the form...  should really pull it out into a forms.py imho too.   I'll probably be cleaning up the code some in the near future so I am taking note of stuff like this.  

For the time being I'd recommend using the form to create/save:
https://github.com/celery/django-celery-beat/blob/master/django_celery_beat/admin.py#L67

**Comment by hartwork** [comment] 2019-04-17 22:16
Hi @liquidpele , thanks for your reply. We have existing code automating creating of certain `PeriodicTask`s during deployment... so we cannot resort to forms.
I would like to vote for re-opening this ticket and to consider calling `validate_unique` from `save` or to do the same validation some other way, on top. Do you have concerns about that approach?

**Comment by liquidpele** [comment] 2019-04-18 00:03
That's fine.

**Comment by charleshan** [comment] 2019-04-27 01:13
@liquidpele  thanks for pointing us to `validate_unique`. I came across this issue today and I agree with @hartwork's suggestion. It really shouldn't be this easy to crash a periodic task schedule manager for a distributed task queue. This library is really important :)

```
# This will crash the beat worker.

PeriodicTask.objects.create(
    name='some_name',
    task='some_task',
    enabled=True,
)
```

I think we should mention the following in the documentation until we find a fix:
> When You're creating a PeriodicTask object in Python, make sure to use `validate_unique()` which checks that you have a unique name and **exactly one schedule** for the task.
```
# Do this instead.
# This will throw ValidationError: {'interval': ['One of interval, crontab, or solar must be set.']}
# before creating the task and your beat worker will be safe.

periodic_task = PeriodicTask(
    name='some_name',
     task='some_task',
     enabled=True,
)
periodic_task.validate_unique()
periodic_task.save()
```

**Comment by liquidpele** [comment] 2019-04-27 13:38
Yea, I agree, especially when the readme/docs say to use the model directly, so I think this should be fixed.  I'm in the middle of a code cleanup right now and have been trying to get all the tests passing on python 3.7 atm, will take a look at fixing some of this usability logic up as well.

**Closed** 2019-06-16 21:14 UTC
