### ISSUE TITLE
No time zone found with key `Asia/Hanoi`

### ISSUE THREAD

**Issue by Carlososuna11** [celery/django-celery-beat#568] opened 2022-08-12 13:36 UTC
### Summary:

* Celery Version:  `5.2.3`
* Celery-Beat Version:  `2.3.0`

### Exact steps to reproduce the issue:
1. Install Celery Beat with the las version of [`pytz`](https://pypi.org/project/pytz/2022.2/)
2. We see this error:  `zoneinfo._common.ZoneInfoNotFoundError: 'No time zone found with key Asia/Hanoi`
In Deep of the error:
```terminal
web_1            |   File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 300, in import_models
web_1            |     self.models_module = import_module(models_module_name)
web_1            |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
web_1            |     return _bootstrap._gcd_import(name[level:], package, level)
web_1            |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
web_1            |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
web_1            |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
web_1            |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
web_1            |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
web_1            |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
web_1            |   File "/usr/local/lib/python3.9/site-packages/django_celery_beat/models.py", line 8, in <module>
web_1            |     import timezone_field
web_1            |   File "/usr/local/lib/python3.9/site-packages/timezone_field/__init__.py", line 1, in <module>
web_1            |     from timezone_field.fields import TimeZoneField
web_1            |   File "/usr/local/lib/python3.9/site-packages/timezone_field/fields.py", line 11, in <module>
web_1            |     class TimeZoneField(models.Field):
web_1            |   File "/usr/local/lib/python3.9/site-packages/timezone_field/fields.py", line 41, in TimeZoneField
web_1            |     default_zoneinfo_tzs = [ZoneInfo(tz) for tz in pytz.common_timezones]
web_1            |   File "/usr/local/lib/python3.9/site-packages/timezone_field/fields.py", line 41, in <listcomp>
web_1            |     default_zoneinfo_tzs = [ZoneInfo(tz) for tz in pytz.common_timezones]
web_1            |   File "/usr/local/lib/python3.9/zoneinfo/_common.py", line 24, in load_tzdata
web_1            |     raise ZoneInfoNotFoundError(f"No time zone found with key {key}")
web_1            | zoneinfo._common.ZoneInfoNotFoundError: 'No time zone found with key Asia/Hanoi'

```

### Detailed information

The latest version of `pytz` includes new zones of which ZoneInfo is unaware. 

### Solution

to solve it you must use `pytz` from the previous version to the current one (`2022.2`).
`pytz==2022.1`

**Comment by auvipy** [comment] 2022-10-13 08:46
was that fixed upstream?

**Comment by auvipy** [comment] 2022-10-13 08:47
duplicate of https://github.com/celery/django-celery-beat/issues/571

**Closed by auvipy** 2022-10-13 08:47 UTC
