### ISSUE TITLE
Tasks are crazy (periodic tasks)

### ISSUE THREAD

**Issue by cesarbecerra** [celery/django-celery-beat#107] opened 2017-12-15 21:51 UTC
I've install 

- celery 4.1.0
-  django-celery-beat 1.10
- django-celery-results 1.0.1
- flower 0.9.2

using redis, when i login in to django admin panel i create a periodic tasks to run every 20 minutes, but when i deploy the server the tasks run every 0.5 seconds.

i go back to older versions

- celery 4.0.2
-  django-celery-beat 1.0.1
- django-celery-results 1.0.1
- flower 0.9.1

and runs flawless

**Comment by mbaechtold** [comment] 2018-01-21 14:55
This issue probably is a duplicate of https://github.com/celery/django-celery-beat/issues/95.

**Closed** 2021-04-25 09:04 UTC
