### ISSUE TITLE
When schedule expires should it not disable the schedule? last run count in this case always keep on increasing

### ISSUE THREAD

**Issue by cs-satish-mishra** [celery/django-celery-beat#240] opened 2019-04-23 08:07 UTC
Why does last run count always keeps on increasing even when schedule is expired . Why it should not be disabled automatically when schedule expires. How can I achieve this? 
Any answer regrading this would be great help. TIA

**Comment by liquidpele** [comment] 2019-05-02 18:53
Sounds like a bug if the task is still running after the schedule expires.  If you figure out how to fix it, please send us a PR!

**Comment by liquidpele** [comment] 2019-05-03 13:26
Also, if you post exact reproduction steps then it can help others who may see the same issue and want to help with a fix.

**Comment by dreamfly32** [comment] 2020-11-06 02:27
i am same problem
django-celery-beat (2.1.0)，celery (5.0.2)
![image](https://user-images.githubusercontent.com/32086491/98318894-92427700-201a-11eb-8aa9-f8c8ab089f51.png)

**Comment by dreamfly32** [comment] 2020-11-06 02:28
@liquidpele

**Comment by auvipy** [comment] 2021-02-12 04:48
are you facing his with the latest release as well?

**Comment by auvipy** [comment] 2021-02-12 04:52
did you give a deep dive on the related code?

**Comment by dreamfly32** [comment] 2021-02-20 02:03
when i disable overdue task, thie problem was  solved. so, when task expires, it should be disabled  @cs-satish-mishra @auvipy @liquidpele

**Comment by auvipy** [comment] 2021-03-03 14:28
> when i disable overdue task, thie problem was solved. so, when task expires, it should be disabled

should we close this issue based on this?

**Comment by salykin** [comment] 2021-09-24 13:01
Same here: ```django==1.11.0 celery==4.4.7 django-celery-beat==1.6.0 python=2.7.13```

I set expires field on more than one day before current time. Beat looks at periodic task, ignores expires field, pushes new task to queue. Worker gets new task and revokes the task right away.

Because I have py2.7, I can`t upgrade Beat to 2.0+ to test with fresh releases.

It looks a little weird. Should Beat create and revoke a task instead of not to create a task at all?

**Comment by auvipy** [comment] 2021-09-27 04:25
you are using outdated python and other packages.

**Comment by cs-satish-mishra** [comment] 2021-09-27 05:56
> you are using outdated python and other packages.

Thanks, Let me try with latest of these packages and confirm about this issue

**Comment by auvipy** [comment] 2021-12-11 10:30
closing for now. please provide more detail if this pop up

**Closed by auvipy** 2021-12-11 10:30 UTC
Labels: More Info Needed
