### ISSUE TITLE
upgraded from beat 1.0.1 to 1.4.0 and beat has died twice in two days

### ISSUE THREAD

**Issue by robvdl** [celery/django-celery-beat#210] opened 2018-12-19 03:59 UTC
We recently upgraded a UAT system from Celery 4.1.1 to 4.2.1 and Beat to 1.4.0

At first glance everything was fine, but twice now has beat process randomly just died and we've had to restart it.

The reason for the upgrade was to switch to the redis-py library version 3, with celery 4.1 we had to pin redis-py to version 2 since the recent redis-py 3 release broke things initially.

Anyway, beat dying has never happened before until we upgraded it, I'll see if I can get some additional information but in the mean time we have to do a rollback to Celery 4.1.1 and Beat 1.0.1

**Comment by robvdl** [comment] 2018-12-19 04:39
The issue with the broken migration 0005 shows up if you try to go from 0006 to 0005:

./manage.py migrate django_celery_beat 0005

CommandError: More than one migration matches '0005' in app 'django_celery_beat'. Please be more specific.

That is because 0005 is that squash migration, it seems to have messed with the order.

**Comment by robvdl** [comment] 2018-12-19 04:45
There are multiple 0006 and multiple 0005 migrations, this thing is a real mess and should be resolved.

It looks like someone did try to resolve it, but you cannot reverse migrate or jump to a specific migration because so many re-used numbers.

**Comment by robvdl** [comment] 2018-12-19 05:14
I also tried to empty all the beat related tables in the Django admin first before migrating back to 0001 and even then it blows up unfortunately.

psycopg2.ProgrammingError: column django_celery_beat_periodictask.solar_id does not exist
LINE 1: ..., "django_celery_beat_periodictask"."crontab_id", "django_ce...

Basically I'm going to have to go into the db and delete the tables and reset the migration state of the django_celery_beat app and just tart again, it looks like the migrations are broken and it simply is not possible to migrate back.

**Comment by justmobilize** [comment] 2018-12-21 06:35
I'm happy to help fix the migrations. Version `1.3.0` and `1.4.0` should be pulled because once they are installed it will be difficult to get fixed. Squashing migrations doesn't work for a package because you never know what someone is on. It's different if you are in control of all the places the code is running.

**Comment by robvdl** [comment] 2018-12-23 02:02
Thanks, in the mean time I've manually rolled back to beat version 1.0.1 and rolled back celery to 4.1.1, because this is a live production system it can't really go down.

I'm going to do some experimentation in the new year to see if I can just upgrade celery but hold back beat for now, it would be nice to find out why beat keeps dying on me but it's a production system for a client so I can't really afford to mess with it too much.

**Comment by auvipy** [comment] 2019-04-23 03:24
Anyone with celery 4.3 or master can verify this issue with celery beat master?

**Comment by robvdl** [comment] 2019-04-23 03:41
After beat suddenly stopped running scheduled tasks after running fine all
night, we've been too scared to try beat 1.4.0 again unfortunately.

We've moved to Celery 4.3 since but are still using beat 1.0.1, also due to
the fact that beat 1.3.0 and 1.4.0 all have broken migrations and cannot be
migrated backwards.

Sadly unless the migrations are fixed, I would not suggest migrating beyond
beat 1.0.1 at this stage. I've been waiting for a 1.5.0 release to fix the
broken migrations, that should be the highest priority on the list as a
project with broken migrations is really really bad. If people need to
migrate their Django project back in production because of a failed
release, you cannot roll back the migrations which is just bad. It happened
to me and I had to manually "fix" the database and undo the migrations. I
was not impressed.

**Comment by auvipy** [comment] 2019-04-23 03:58
I can see a migration change here, https://github.com/celery/django-celery-beat/compare/v1.4.0...master could you please try on local using from the master branch?

**Comment by robvdl** [comment] 2019-04-23 09:17
I had a quick look at the diff between v1.4.0...master and the only
migration I can see is another addition adding a field. That won't be the
fix we are looking for unfortunately.

See issue #217 about the broken migrations, they don't seem to be fixed and
it's holding people back from accepting the new version. People don't feel
safe if they can't migrate backwards.

As I recall looking into it earlier this year, people have messed with
migration history, and/or squashing migrations. You basically cannot
migrate backwards now.

**Comment by robvdl** [comment] 2019-04-23 09:21
Basically to test this, start a project with beat 1.0.1, then upgrade to beat 1.4.0 and apply the migrations, then migrate the django_celery_beat app back to migration 0001, it will fail.

**Comment by robvdl** [comment] 2019-04-23 09:30
Actually issue #217 doesn't accurately explain the issue, the comments in this issue do.

The issue #217 seems to end with "don't edit migrations that have already been applied". I beg to differ, sure that is the case normally, but if the migrations are broken then you basically have no choice to fix them to resolve this mess in this particular case.

**Comment by justmobilize** [comment] 2019-04-23 18:19
One could clean up the migrations, and create a new one that may need some insane logic to fix past mistakes. For new installs it would be fine since there would be no data. Some people may just need to rebuild their schedules

**Comment by auvipy** [comment] 2019-04-24 02:21
@robvdl can you come with a solution?

**Comment by justmobilize** [comment] 2019-04-24 17:17
I'm happy to work through this (As I've said in #217).

I just want to make sure my time isn't wasted and that I'll get active support in getting it figured out and merged.

**Comment by auvipy** [comment] 2019-04-24 17:25
I have dedicated time to help maintain these projects, so, please proceed and mention me in the new PR

**Comment by justmobilize** [comment] 2019-04-24 17:28
Awesome. Thanks!

**Comment by justmobilize** [comment] 2019-04-24 18:54
@robvdl, can we start with this?

- Install v1.4.0
- Apply this [patch](https://gist.github.com/justmobilize/baf52f364d644d362d5944adb7bc7c73)

You should be able to migrate frontwards and backwards.

The next question is migrations aside, does the beat process still die?

Also, not sure on your timezone settings, I needed to add this:
```
from django.utils import timezone
app.now = timezone.now
```
To my celery app

**Comment by liquidpele** [comment] 2019-04-25 00:45
> Some people may just need to rebuild their schedules

I would *really* like to avoid that.  If necessary, we can always use the migrations.RunPython to manually fix things if we need to do something crazy.

**Comment by auvipy** [comment] 2019-04-25 04:01
@tinylambda

**Comment by justmobilize** [comment] 2019-04-25 05:11
I agree. First step is to solve the problem, then find out how to make it work.

In theory if you are in a working state tweaking existing migrations wont hurt assuming the final state is the same.

**Comment by justmobilize** [comment] 2019-04-25 17:19
@auvipy and @liquidpele, do you have any idea what versions you have in the wild?

Doing so testing I found:
```
v1.0.0 -> to my fix - okay
v1.0.1 -> to my fix - okay
v1.1.0 -> to my fix - okay
v1.1.1 -> to my fix - okay
v1.2.0 -> to my fix - not okay
v1.3.0 -> to my fix - okay
v1.4.0 -> to my fix - okay
```

also that a fresh install of `v1.3.0` or `v1.4.0` can not migrate

so worst case if someone is on `v1.2.0` they would need to upgrade to `v1.4.0` first. Does that seem acceptable?

**Comment by justmobilize** [comment] 2019-04-25 21:52
@robvdl, I've had it running to 24 hours and processed about 250k tasks without any issues. Would love to know if you did (realizing the crashing and migrations have nothing to do with each other)

**Comment by robvdl** [comment] 2019-04-26 00:27
Sorry I won't be able to get a chance to try this again for a while, but I will eventually. One issue is that the servers this runs on are still on trusty and we've been trying to convince the client for a year they need upgrading.

**Comment by liquidpele** [comment] 2019-04-29 04:29
I've fixed the migration issue and added tests for it in my PR since I was adding a new migration anyway.  https://github.com/celery/django-celery-beat/pull/241

I was easily able to reproduce issues by just migrating back to 0001 and then forward again on django 1.11.20.  @justmobilize care to retest with my branch?

**Comment by justmobilize** [comment] 2019-04-29 16:06
@liquidpele, you deleted migrations, meaning if someone is on another version they will be totally blocked from moving forward (for example my production environment is on 1.1.1 which ends on 0005).

I would highly recommend tossing `0005_add_solarschedule_events_choices_squashed_0009_merge_20181012_1416` in favor of the patch I have above.

Thoughts?

**Comment by justmobilize** [comment] 2019-04-29 16:07
You could then after that, make a squash `0001` through `0010` that you keep forever to make new installs quicker.

**Comment by robvdl** [comment] 2019-05-02 03:20
I like this solution :) I'm going to give this another shot in the next few weeks when I have a chance.

**Comment by auvipy** [comment] 2021-03-04 07:58
#244

**Closed by auvipy** 2021-03-04 07:58 UTC
