### ISSUE TITLE
scheduler wont lauch tasks if DatabaseScheduler: Schedule changed. 

### ISSUE THREAD

**Issue by marco-silva0000** [celery/django-celery-beat#35] opened 2017-04-13 10:37 UTC
I have a Model that generates a PeriodicTask with CrontabSchedule, and sometimes there are 2 or 3 of those tasks at the same time. everytime a new Model instance is saved or edited, the Schedule will change, so the DatabaseScheduler resyncs everything. If this happens near the full minute mark, when some new tasks are bound to be launched, they never are as the process is busy with rescheduling and wont launch those scheduled tasks.

you can recreate this by:

setting up a bunch of tasks every minute
```
from djcelery.models import CrontabSchedule, PeriodicTask
crontab = CrontabSchedule.objects.create(minute='*')
tasks = ['task1', 'task2', 'task3', 'task4', 'task5', 'task6', 'task7', 'task8', 'task9', ]
for task in tasks:
    PeriodicTask.objects.create(name=task, crontab=crontab)
```
generating a new task, in seccond 59 of any minute
`PeriodicTask.objects.create(name='interruptor1', crontab=crontab)`

you will see the beat log prompt a schedule change and it wont launch the shceduled tasks.

**Comment by marco-silva0000** [comment] 2017-04-13 10:39
I was thinking what would be the best way to fix this and im happy to submit a PR if I can find anything

In my speciefic case, the problem is worse because the lunched task will save the Model instance and always prompt a new rescheduling of tasks, so if 2 or 3 are bound to run, and the first one finishes before the scheduler lunches everything, the problem will happen

**Comment by rh0dium** [comment] 2017-05-20 19:23
Hi there,

I can confirm this is a problem.
The simplest way to reproduce this is to create a task like so

```
@periodic_task(run_every=datetime.timedelta(minutes=2), options={"expires": 90})
def periodic_test(**kwargs):
    print("Running Task")

```

Then restart both services

```
celery -A celery_app worker --events -B -S django -l debug
celery -A celery_app events -l debug --camera django_celery_monitor.camera.Camera --frequency=2
```

Finally go into the periodic tasks in django admin and change a value or disable any other periodic task. _As reported in in another issue the schedule doesn't change even though it is committed to the db._   

If you then stop and restart the services and it will no longer schedule anything.    To rectify the situation I found I can delete all periodic tasks and restart both the celery worker and camera and viola everything is back to normal.

FYI:

```
celery -A celery_app report

software -> celery:4.0.2 (latentcall) kombu:4.0.2 py:2.7.10
            billiard:3.5.0.2 py-amqp:2.1.4
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:django-db

CELERY_BROKER_PORT: u'5672'
CELERY_RESULT_SERIALIZER: u'json'
CELERY_BROKER_URL: u'amqp://icmadmin:********@localhost:5672/icmanage'
CELERY_TASK_TIME_LIMIT: 28800
CELERY_TASK_TRACK_STARTED: True
CELERY_WORKER_CONCURRENCY: 4
CELERY_BROKER_HOST: u'localhost'
CELERY_BROKER_USER: u'icmadmin'
CELERY_RESULT_BACKEND: u'django-db'
CELERY_TASK_SERIALIZER: u'json'
CELERY_BROKER_PASSWORD: u'********'
CELERY_ACCEPT_CONTENT: [u'json']
CELERY_BEAT_SCHEDULER: u'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_SEND_EVENTS: True
CELERY_SEND_TASK_ERROR_EMAILS: True

```

**Closed** 2018-12-11 10:22 UTC

**Comment by fatruchir0** [comment] 2023-05-16 15:39
@auvipy - this is still happening on `django-celery-beat==2.2.1` - could you please help me with if this would be fixed? or if there's a workaround?

**Comment by hosam7080** [comment] 2024-02-01 13:08
@auvipy this issue still exist, I don't know why you closed it

**Comment by tatsuya-satake** [comment] 2024-10-17 01:59
This is still happening on `django-celery-beat===2.5.0`.

**Comment by cclauss** [comment] 2024-10-17 05:55
https://github.com/celery/django-celery-beat/releases

**Comment by sehmaschine** [comment] 2024-12-20 11:48
still seeing this with 2.6.0 (and does not seem to be fixed with 2.7.0)

**Comment by votming** [comment] 2025-03-11 11:03
I'm still experiencing this issue with version 2.7.0. I have a RabbitMQ listener inside my Django app that schedules Periodic Tasks. However, whenever a new task is created, all other scheduled tasks are skipped for a certain time window. Since my listener creates tasks every minute (or even more frequently, such as every 10 seconds), any tasks with an interval greater than that 10 secs are never executed.
