### ISSUE TITLE
Interval tasks not running but crontabs are, USE_TZ=True (works <= v1.1.1)

### ISSUE THREAD

**Issue by ses4j** [celery/django-celery-beat#279] opened 2019-08-09 17:36 UTC
### Summary:

We have a 15 second interval task and some crontabs.  The interval stopped firing when we upgraded from 1.0.1 to 1.5.0, though crontabs still fire.  

* Celery Version: 4.3.0
* Celery-Beat Version: 1.1.1 works, 1.2.0 and 1.5.0 broken

### Detailed information
* Noticed in `select * from django_celery_beat_periodictask` that the `last_run_at` WAS updating frequently, but the event itself never seemed to actually be happening.
* USE_TZ=True
* Computer's TZ = UTC.
* CELERY_TIMEZONE is not set.

**Comment by romainr** [comment] 2019-08-11 18:08
Seeing the same scenario

**Comment by auvipy** [comment] 2019-08-15 06:35
did you find out the root cause of the regression?

**Comment by yarinb** [comment] 2019-09-01 13:03
I am facing the exact same behavior. Looks like a regression indeed.
Intermittently, periodic tasks that do have an interval, just don't run. More often then not - the last_run_at is empty and never gets updated.

Triggering the task manually through Django admin works just fine.

**Comment by SHIWWW** [comment] 2019-10-13 10:55
+1

**Comment by de-don** [comment] 2019-10-30 03:47
I have the same issue

**Comment by ses4j** [comment] 2019-12-13 14:23
Is there anything I can do to improve this report?  I would like to upgrade but cannot, and don't really know how to debug further.

**Comment by superandrew** [comment] 2020-02-15 22:16
i never tried with earlier version, but can confirm that after a lot of debugging, our similar problem seems to be with this package (on version 1.5.0 and 1.6.0). Interval and crontabs are never executed, while celery beat running on persistency mode fire them regularly.

**Comment by jaydipkmn** [comment] 2020-04-07 07:21
We are facing same issue. The periodic task is running with Interval schedule. Now we disable periodic task for hours or so and then if we enable it again it did not get run. However if we trigger task manually or run with crontab schedule then after it is running fine with Interval schedule. Looks like the issue is with last_run_at as mentioned by @yarinb . Running manually or through crontab will set the last_run_at and then it is working fine.
@ses4j The workaround here is that change the Intervals to contab schedule if possible. We did it and it is working fine.

**Comment by auvipy** [comment] 2021-09-11 16:57
should be fixed by latest release.

**Closed by auvipy** 2021-09-11 16:57 UTC
