### ISSUE TITLE
Interval schedules do not work when Django timezone and Celery timezone are different

### ISSUE THREAD

**Issue by DDevine** [celery/django-celery-beat#67] opened 2017-07-28 01:06 UTC
As the title says. 
I guess this was an oversight that I should have caught when working on my previous PRs.

**Comment by marco-silva0000** [comment] 2017-07-28 10:38
I was just finding about this error.
I have the sample tasks running with the default scheduler fine, but when using the database scheduler of this package i have infinite calls on the task, because the is_due call of this type event always is true.
the celery.schedules.schedule class makes this call self.maybe_make_aware(last_run_at)
 print self.maybe_make_aware(last_run_at) gives me this 2017-07-28 10:27:06.436527 when my current timezone is one hour more, so the rem_delta = -1 day, 23:23:08.922251
i have the following settings
TIME_ZONE = 'Europe/Lisbon'
CELERY_ENABLE_UTC = True
CELERY_TIMEZONE = 'Europe/Lisbon'

I can help fixing this if you give me any pointers, in the meanwhile, is there som other version that does not have this problem?

**Comment by DDevine** [comment] 2017-08-01 23:16
There has been some recent changes to Celery, and I've also fixed some things too - notably I have made last_run_at timezone aware which may solve your issue because the delta might be calculated correctly. 
You could try the code in this pull request: https://github.com/celery/django-celery-beat/pull/68

**Comment by 2ps** [comment] 2018-03-11 05:09
This issue is likely caused by stupidity in Celery 4.1.0 -- where they couldn't figure out how to calculate now properly for non-UTC timezones.  You can fix it by subclassing from `celery.Celery` and writing your own `now` function that returns a properly timezoned now (e.g., `datetime.now(my_timezone)`).

**Comment by DDevine** [comment] 2018-03-11 05:25
@2ps is that a fix or a hack?

Patches welcome - negativity isn't. Remember, contributors (and/or their employers or customers) pay a price for the work they put in. Put your patches where you mouth is.

**Comment by harelw** [comment] 2018-03-13 19:27
Looks like most recent Celery takes inherits timezeone from Django by default. I ran into problems when I set CELERY_TIMEZONE to the same value as TIME_ZONE manually. The fix was simply to remove CELERY_TIMEZONE and null out last_run_at for each task.

**Comment by gdvalderrama** [comment] 2018-04-16 14:24
@harelw Could you detail what problems you ran into?
I was just trying to do that since beat is using UTC instead of TIME_ZONE.

**Comment by qburst-starsona** [comment] 2018-08-30 14:36
You can try the `nowfun` argument in `crontab` for setting different timezone

https://stackoverflow.com/questions/21827290/celery-beat-different-time-zone-per-task

**Comment by auvipy** [comment] 2021-03-03 14:39
should be fixed in newer versions

**Closed by auvipy** 2021-03-03 14:39 UTC
